CREATE TABLE IF NOT EXISTS cms_pages (route VARCHAR(190) PRIMARY KEY, title VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS cms_content (page VARCHAR(190) NOT NULL, field_key VARCHAR(40) NOT NULL, prop VARCHAR(40) NOT NULL, label TEXT NOT NULL, value MEDIUMTEXT NOT NULL, PRIMARY KEY(page,field_key,prop));
CREATE TABLE IF NOT EXISTS cms_users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(100) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS cms_login_attempts (ip_hash CHAR(64) PRIMARY KEY, attempts INT NOT NULL DEFAULT 0, last_attempt BIGINT NOT NULL);
